[project]
name = "simple_lan_scanner"
version = "0.1"

[project.optional-dependencies]
cli = ["click >=8.1"]

[project.scripts]
lan-scan     = "simple_scanner.cli:app"
lan-scan-gui = "simple_scanner.gui:main"